

```
make build        # Собрать Docker образы
make up           # Запустить контейнеры в фоне
make logs         # Смотреть все логи
make logs-fastapi # Смотреть только логи FastAPI
make restart      # Перезапустить все контейнеры
make clean        # Полная очистка Docker ресурсов
make shell        # Зайти в контейнер FastAPI

```